# Generated by Django 5.2.6 on 2025-09-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='size',
            field=models.CharField(blank=True, help_text='e.g., 1.47 GB', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='codename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
