# Generated by Django 5.2.6 on 2025-09-25 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_brand_device_release_date_device_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='size',
        ),
        migrations.RemoveField(
            model_name='device',
            name='version',
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_version', models.CharField(max_length=20)),
                ('build_version', models.CharField(max_length=20)),
                ('build_type', models.CharField(default='userdebug', max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('is_maintained', models.BooleanField(default=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('download_link', models.URLField()),
                ('changelog_link', models.URLField(blank=True)),
                ('install_guide_link', models.URLField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='devices.device')),
            ],
        ),
    ]
