# Generated by Django 5.2.6 on 2025-09-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_device_release_date_remove_device_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='maintainer_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
