# Generated by Django 5.2.6 on 2025-09-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_maintainer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latest_version',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='released_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='size',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
    ]
