# Generated by Django 5.2.6 on 2025-09-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_latest_version_device_released_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='download_latest',
            field=models.URLField(blank=True, null=True),
        ),
    ]
