# Generated by Django 5.2.6 on 2025-09-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_download_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='download_latest',
        ),
    ]
