# Generated by Django 5.2.6 on 2025-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='Upload a square image (e.g., 200x200).', null=True, upload_to='team_avatars/')),
            ],
        ),
    ]
